---
deployment:
      tasks:
        - export DEPLOYPATH=/home/ucanmedya/tiklaparakazan.com/     
        - /bin/cp /home/ucanmedya/tiklaparakazan.com/classic.html $DEPLOYPATH                      
      
        
        
